import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    nav_home: "Home",
    nav_services: "Services",
    nav_order: "Order Now",
    nav_admin: "Office Login",
    hero_badge: "Premium Printing & Advertising",
    hero_elevate: "Elevate Your",
    hero_btn_start: "Start Your Order",
    hero_btn_explore: "Explore Services",
    hero_studio_title: "Creative Studio",
    hero_studio_subtitle: "Printing & Full Stack Digital",
    hero_experience: "10yr+",
    "Printing Services": "Printing Services",
    "Advertising": "Advertising Agency",
    "Web & App Development": "Web & App Development",
    "Gift Equipment Making": "Gift Equipment Making",
    details_back: "Back to Home",
    details_subtitle: "Explore our featured items and services. Leave a like or a private message for details!",
    details_loading: "Loading services...",
    details_empty: "No items added for this service yet.",
    details_voice_order: "Order via Voice",
    details_text_order: "Order via Text",
    details_feedback_title: "Private Questions",
    details_feedback_desc: "Have a question? Drop a private message here.",
    details_feedback_success: "Sent to our office!",
    details_feedback_placeholder: "Type message...",
    details_img_placeholder: "No Image",
    opt_select: "Select a Service",
    opt_printing: "Printing (Student, Office, Personal)",
    opt_advertising: "Advertising & Branding",
    opt_web: "Web & App Development",
    opt_gift: "Gift Equipment Making",
    opt_other: "Multiple / Other",
    order_submitting: "Submitting...",
    order_title: "Project Inquiry",
    order_subtitle: "Tell us about your needs and we'll get back to you soon.",
    order_first_name: "First Name",
    order_last_name: "Last Name",
    order_email: "Email Address",
    order_service: "Service Required",
    order_details: "Message Details",
    order_submit: "Submit Request",
    order_placeholder_fname: "John",
    order_placeholder_lname: "Doe",
    order_placeholder_email: "john@example.com",
    order_placeholder_details: "Project goals...",
    footer_rights: "All rights reserved.",
    footer_tagline: "Shikret Advert and Gift — Excellence in every print.",
    footer_contact_info: "Connect with us or visit our office.",
    lang_en: "English",
    lang_am: "አማርኛ",
    lang_or: "Oromiffa",
    services_title: "Our Capabilities",
    services_subtitle: "Full-stack solutions for printing and digital needs.",
    services_explore: "Explore",
    services_no_items: "No services yet.",
    services_click_hint: "View all details"
  },
  am: {
    nav_home: "መነሻ",
    nav_services: "አገልግሎቶች",
    nav_order: "አሁን ይዘዙ",
    nav_admin: "የቢሮ መግቢያ",
    hero_badge: "ጥራት ያለው ህትመትና ማስታወቂያ",
    hero_elevate: "ያሳድጉ",
    hero_btn_start: "ትዕዛዝ ይጀምሩ",
    hero_btn_explore: "አገልግሎቶችን ያስሱ",
    hero_studio_title: "የፈጠራ ስቱዲዮ",
    hero_studio_subtitle: "ህትመት እና ዲጂታል ስራዎች",
    hero_experience: "10ዓመት+",
    "Printing Services": "የህትመት አገልግሎቶች",
    "Advertising": "የማስታወቂያ ድርጅት",
    "Web & App Development": "የድረገጽ እና ሶፍትዌር ስራዎች",
    "Gift Equipment Making": "የስጦታ ዕቃዎች ማምረት",
    details_back: "ወደ መነሻ ተመለስ",
    details_subtitle: "አገልግሎቶቻችንን እዚህ ይቃኙ። ጥያቄ ካለዎት በቀጥታ መልዕክት መላክ ይችላሉ።",
    details_loading: "በመጫን ላይ...",
    details_empty: "ለዚህ አገልግሎት እስካሁን የተገለጸ ዝርዝር የለም።",
    details_voice_order: "በድምፅ መልዕክት እዘዝ",
    details_text_order: "በትዕዛዝ ዝርዝር እዘዝ",
    details_feedback_title: "የግል አስተያየት እና ጥያቄ",
    details_feedback_desc: "ስለዚህ ዕቃ ጥያቄ አለዎት? እዚህ መልዕክት ይጻፉ—በቀጥታ ለቢሯችን ይደርሳል።",
    details_feedback_success: "መልዕክትዎ ለቢሯችን ደርሷል!",
    details_feedback_placeholder: "ጥያቄዎን እዚህ ይጻፉ...",
    details_img_placeholder: "ምስል የለም",
    opt_select: "አገልግሎት ይምረጡ",
    opt_printing: "ህትመት (ተማሪ፣ ቢሮ፣ የግል)",
    opt_advertising: "ማስታወቂያ እና ብራንዲንግ",
    opt_web: "ድህረ ገጽ እና ሶፍትዌር",
    opt_gift: "የስጦታ ዕቃዎች ማምረት",
    opt_other: "ሌሎች / ተጨማሪ",
    order_submitting: "በመላክ ላይ...",
    order_title: "የፕሮጀክ መጠይቅ",
    order_subtitle: "ስለ ፍላጎታቸው ይንገሩን፣ በቅርቡ ምላሽ እንሰጥዎታለን።",
    order_first_name: "መጀመሪያ ስም",
    order_last_name: "የአያት ስም",
    order_email: "ኢሜል አድራሻ",
    order_service: "የሚፈልጉት አገልግሎት",
    order_details: "የመልዕክት ዝርዝር",
    order_submit: "ትዕዛዝ ላክ",
    order_placeholder_fname: "ዮናስ",
    order_placeholder_lname: "ከበደ",
    order_placeholder_email: "yonas@example.com",
    order_placeholder_details: "ስለ ፕሮጀክትዎ...",
    footer_rights: "መብቱ የተጠበቀ ነው።",
    footer_tagline: "ሽክረት ማስታወቂያ እና ስጦታ — በእያንዳንዱ ህትመት የላቀ ውጤት።",
    footer_contact_info: "ያግኙን ወይም በደብረ ብርሃን ቢሮአችን ይምጡ።",
    lang_en: "English",
    lang_am: "አማርኛ",
    lang_or: "Oromiffa",
    services_title: "አገልግሎታችን",
    services_subtitle: "ለህትመት እና ዲጂታል ስራዎች የተሟላ መፍትሄ።",
    services_explore: "ተመልከት",
    services_no_items: "ምንም አገልግሎት የለም።",
    services_click_hint: "ዝርዝሩን ይመልከቱ"
  },
  or: {
    nav_home: "Mana",
    nav_services: "Tajaajila",
    nav_order: "Amma Ajajaa",
    nav_admin: "Seensa Ofisii",
    hero_badge: "Maxxansa fi Beeksisa",
    hero_elevate: "Ol Kaasaa",
    hero_btn_start: "Ajaja Jalqabaa",
    hero_btn_explore: "Tajaajila Sakatta'aa",
    hero_studio_title: "Istuudiyoo Kalaqaa",
    hero_studio_subtitle: "Maxxansa fi Hojii Dijitaalaa",
    hero_experience: "10w+",
    "Printing Services": "Tajaajila Maxxansaa",
    "Advertising": "Dhaabbata Beeksisaa",
    "Web & App Development": "Misooma Weebsaayitii",
    "Gift Equipment Making": "Meeshaalee Kennaa Oomishuu",
    details_back: "Gara Manaatti Deebi'i",
    details_subtitle: "Meeshaalee keenya hunda asitti argattu.",
    details_loading: "Fe'amaa jira...",
    details_empty: "Ibsi dabalataa hin jiru.",
    details_voice_order: "Ergaa Sagaleetiin",
    details_text_order: "Ergaa Barreeffamaatiin",
    details_feedback_title: "Yaada Dhuunfaa",
    details_feedback_desc: "Gaaffii qabduu? Nu qunnamaa.",
    details_feedback_success: "Nagaan darbeera!",
    details_feedback_placeholder: "Asitti barreessaa...",
    details_img_placeholder: "Fakkii hin jiru",
    opt_select: "Tajaajila Filadhaa",
    opt_printing: "Maxxansa (Barataa, Ofisii, Dhuunfaa)",
    opt_advertising: "Beeksisa fi Brandaingii",
    opt_web: "Misooma Weebsaayitii",
    opt_gift: "Meeshaalee Kennaa Oomishuu",
    opt_other: "Kan biraa",
    order_submitting: "Ergamaa jira...",
    order_title: "Gaaffii Piroojektii",
    order_subtitle: "Waa'ee fedhii keessanii nuatti himaa.",
    order_first_name: "Maqaa Duraa",
    order_last_name: "Maqaa Abbaa",
    order_email: "Imeelii",
    order_service: "Tajaajila Barbaadamu",
    order_details: "Ibsa Ergaa",
    order_submit: "Ajaja Ergi",
    order_placeholder_fname: "Abbebe",
    order_placeholder_lname: "Caalaa",
    order_placeholder_email: "abbebe@example.com",
    order_placeholder_details: "Waa'ee piroojektii keessanii...",
    footer_rights: "Mirgi hundu eegame dha.",
    footer_tagline: "Shikret — Maxxansa hunda irratti dandeettii ol'aanaa.",
    footer_contact_info: "Nu qunnamaa ykn biiroo keenya daawwadhaa.",
    lang_en: "English",
    lang_am: "አማርኛ",
    lang_or: "Oromiffa",
    services_title: "Dandeettii Keenya",
    services_subtitle: "Furmaata guutuu maxxansa fi dijitaalaaf.",
    services_explore: "Sakatta'aa",
    services_no_items: "Hojiin dabalataa hin jiru.",
    services_click_hint: "Ibsa guutuu argachuuf"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('preferred_language') || 'en');

  useEffect(() => {
    localStorage.setItem('preferred_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
